apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo  
  labels:
    app: api-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
      - name: api-demo
        image: api-demo
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
